title: BookCheeGo User Manual
description: A User manulal for BookcheeGo
theme: just-the-docs

url: https://mskim.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
